development:
  adapter: async

test:
  adapter: test

test:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: jcars_test

production:
  adapter: redis
  url: ENV['REDIS_URL']
  channel_prefix: jcars_production
  ssl: true