development:
  adapter: async


test:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: jcars-app_test

production:
  adapter: redis
  url: <%= ENV['REDIS_URL'] %>
  channel_prefix: jcars-app_production
  ssl_params:
    verify_mode: OpenSSL::SSL::VERIFY_NONE